export  const Initial = [
    {
        id:1,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:2,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:3,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:4,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:5,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:6,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:7,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:8,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:9,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:10,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:11,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    },
    {
        id:12,
        name:"Vraj Patel",
        type:"phsychologist",
        modes:["audio","video"],
        skills:["love","relationship","marraige","anger","mood swings"],
        price:"$ 125",
        education:"Msc. in physcology",
        experience:"Expert counseller at corporates",
        summary:"Priya Patel is a trained Psychologist, psychotherapist with 5 years of experience in the field of Psychology, mental Health and Psychotherapy, working with corporate, family, work related, clinical assessments and psychotherapy for both children and adults from different age groups and cultural background.",
        profileSaurce:"../../frontend-designs/profile.png",
        ratingSaurce:"../../frontend-designs/star.png",
    }
    
] 